import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react';
import dynamic from 'next/dynamic';
import GetPlaylist from '../components/GetPlaylist';
import { Container } from '@mui/material';
const ReactPlayer = dynamic(() => import("react-player"), { ssr: false });


const Home: NextPage = () => {
  const [songs, setSongs] = useState<any[]>([])

  return (
    <Container sx={{ pt: 3 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GetPlaylist setSongs={setSongs} />
      {songs.length === 0 ?
        null
        :
        <ReactPlayer
          controls
          // url={'https://www.youtube.com/watch?v=' + songs[0].snippet.resourceId.videoId}
          url='https://www.youtube.com/watch?v=15gGZQNlDVo&list=PL4GgJODQxydGVmSyYDn_zF4OS6w4Lw2p8&index=2'
          playing={true}
        />
      }
    </Container>
  )
}

export default Home

